import React,{useEffect,useRef,useState} from 'react';
import type { CharacterProfile,UserProfile } from '../../../types';
import { FISHING_MARKET_STORAGE_KEY,mutateFishingMarket,readFishingMarketState,type FishingMarketState,type MarketActor } from '../../../utils/vrWorld/fishingMarket';
import { ensureDinosaurGarden,syncGardenToys,gardenResidents,gardenSlots,gardenCatchAvailable,editDino,findGardenSpace,gardenComment,setGardenMap,setGardenVisits,editGardenProp,giftDino,undoGardenVisit } from '../../../utils/vrWorld/dinosaurGarden';
import { DINO_CATALOG,DINO_PALETTES,PROP_LABELS,defaultDinoPaint,dinoDefinition } from '../../../utils/vrWorld/dinosaurCatalog';
import { activeGardenMap,DINO_ACTIONS,type DinoAction,type DinoPaint,type GardenPropKind,type GardenEvent,type DinoPose } from '../../../utils/vrWorld/dinosaurTypes';
import { createGardenRenderer } from './renderer';
import './garden.css';

type Sheet='paint'|'stage'|'theme'|'props'|'visits'|'history'|'profile'|'details'|null;
interface Props {userProfile:UserProfile;characters:CharacterProfile[];onClose:()=>void;onCharacterTrip:(char:CharacterProfile)=>Promise<{ok:boolean;reason?:string}>;demo?:boolean}
const stamp=(at:number)=>new Date(at).toLocaleString(undefined,{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
import { DinoIcon } from './DinoIcon';
export function DinosaurGarden({userProfile,characters,onClose,onCharacterTrip,demo=false}:Props){
  const [state,setState]=useState<FishingMarketState|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
  const [selected,setSelected]=useState(''),[tab,setTab]=useState<'garden'|'catalog'>('garden'),[sheet,setSheet]=useState<Sheet>(null),[placing,setPlacing]=useState<string|null>(null);
  const [paint,setPaint]=useState<DinoPaint|null>(null),[action,setAction]=useState<DinoAction>('发呆'),[words,setWords]=useState(''),[target,setTarget]=useState(''),[nickname,setNickname]=useState(''),[visitor,setVisitor]=useState(''),[trip,setTrip]=useState(false),[historyPage,setHistoryPage]=useState(0),[giftTarget,setGiftTarget]=useState(''),[historyToy,setHistoryToy]=useState<string|null>(null),[focus,setFocus]=useState<{id:string;before?:DinoPose|null}|null>(null);
  const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof createGardenRenderer>|null>(null),busyRef=useRef(false),current=useRef({state,selected,placing});current.current={state,selected,placing};
  const user:MarketActor={id:'user',name:userProfile.name||'我',kind:'user'};
  const g=state?.dinosaurGarden,map=g?activeGardenMap(g):undefined,toy=g?.toys[selected],owned=state?.inventory.filter(c=>(c.ownerId==='user'||characters.some(char=>char.id===c.ownerId))&&dinoDefinition(c.speciesId))||[],residents=state?gardenResidents(state):[];
  const editable=!!state&&!!toy&&gardenCatchAvailable(state,toy.catchId,state.inventory.find(c=>c.id===toy.catchId)?.ownerId),onThisMap=!!toy?.pose&&toy.mapId===g?.activeMapId,portrait=sheet==='paint'||sheet==='details';
  async function commit(change:(s:FishingMarketState)=>FishingMarketState,message?:string){if(busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');try{const next=await mutateFishingMarket(s=>change(syncGardenToys(s)));setState(next);if(message)setNotice(message);return true;}catch(e){setError(e instanceof Error?e.message:String(e));return false;}finally{busyRef.current=false;setBusy(false);}}
  const choose=(id:string)=>{setSelected(id);setPlacing(null);setPaint(null);setNotice('');};
  useEffect(()=>{let alive=true;void mutateFishingMarket(s=>ensureDinosaurGarden(s,user)).then(s=>{if(alive){setState(s);setSelected(gardenResidents(s)[0]?.catchId||s.inventory.find(c=>(c.ownerId==='user'||characters.some(char=>char.id===c.ownerId))&&dinoDefinition(c.speciesId))?.id||'');}}).catch(e=>{if(alive)setError(e.message);});
    const refresh=()=>{try{const next=syncGardenToys(readFishingMarketState());if(alive)setState(next);}catch(e){if(alive)setError((e as Error).message);}};
    const storage=(e:StorageEvent)=>{if(e.key===FISHING_MARKET_STORAGE_KEY)refresh();};window.addEventListener('vr-fishing-market-updated',refresh);window.addEventListener('storage',storage);
    return()=>{alive=false;window.removeEventListener('vr-fishing-market-updated',refresh);window.removeEventListener('storage',storage);};
  },[]);
  useEffect(()=>{if(!host.current)return;try{engine.current=createGardenRenderer(host.current,{ready:()=>setReady(true),error:setError,select:choose,place:pose=>{const c=current.current;if(!c.placing)return;void commit(s=>c.placing!.startsWith('prop:')?editGardenProp(s,user,{id:c.placing!.slice(5),pose:{...pose,rotation:activeGardenMap(s.dinosaurGarden!).props.find(p=>p.id===c.placing!.slice(5))?.rotation||0}}):editDino(s,user,c.selected,{pose}),'摆好了。').then(ok=>{if(ok)setPlacing(null);});}});}catch{setError('这台设备暂时无法显示 3D 箱庭，收藏和记录仍可查看。');}return()=>{engine.current?.dispose();engine.current=null;};},[]);
  useEffect(()=>{if(state?.dinosaurGarden)void engine.current?.sync(state,selected,portrait?'portrait':'garden',paint||undefined).then(()=>{if(focus){engine.current?.highlight(focus.id,focus.before);setFocus(null);}});},[state,selected,portrait,paint,focus]);
  useEffect(()=>{engine.current?.place(!!placing);},[placing]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{const w=window as Window&{render_game_to_text?:()=>string;advanceTime?:(ms:number)=>void};const old=w.render_game_to_text,advance=w.advanceTime;
    const render=()=>JSON.stringify({mode:'dinosaur-garden',tab,sheet,selected,placing,mapId:g?.activeMapId,maps:g?.maps.map(m=>({id:m.id,name:m.name,count:state?gardenResidents(state,m.id).length:0})),theme:map?.theme,visits:g?.visitsEnabled,residents:residents.map(t=>({id:t.catchId,species:t.speciesId,name:t.name,paint:t.paint,pose:t.pose,stage:t.stage,fixed:t.fixed})),events:g?.events.slice(-4),render:engine.current?.metrics(),floorTargets:(state?gardenSlots(state,selected):[]).map(p=>({...p,screen:engine.current?.project(p)})),props:map?.props});
    const step=(ms:number)=>engine.current?.advance(ms);w.render_game_to_text=render;w.advanceTime=step;
    const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSheet(null);setPaint(null);setPlacing(null);}if(e.target===document.body&&e.code==='Space'){e.preventDefault();engine.current?.greet();}if(e.target===document.body&&e.key==='f'){if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>{});}};document.addEventListener('keydown',key);
    return()=>{if(w.render_game_to_text===render)w.render_game_to_text=old;if(w.advanceTime===step)w.advanceTime=advance;document.removeEventListener('keydown',key);};
  },[state,selected,placing,tab,sheet]);
  const open=(next:Sheet)=>{setPlacing(null);setWords('');setError('');if(next==='paint'&&toy)setPaint({...toy.paint});if(next==='stage'&&toy){setAction(toy.userStage.action);setWords(toy.userStage.text);setTarget(toy.userStage.targetId||'');}if(next==='profile'&&toy)setNickname(toy.name);if(next==='history')setHistoryPage(0);setSheet(next);};
  const closeSheet=()=>{setSheet(null);setPaint(null);setWords('');};
  const unread=g?g.events.slice(Math.max(0,g.events.findIndex(e=>e.id===g.seenEventId)+1)).filter(e=>e.actorKind==='character'):[];
  const showHistory=(all=false)=>{setHistoryToy(all?null:selected);open('history');if(g?.events.length)void commit(s=>({...s,dinosaurGarden:{...s.dinosaurGarden!,seenEventId:g.events.at(-1)!.id}}));};
  const history=(g?.events||[]).filter(e=>!historyToy||e.toyId===historyToy||!e.toyId).slice().reverse();
  const focusEvent=(e:GardenEvent)=>{if(e.toyId){void commit(s=>setGardenMap(s,s.dinosaurGarden!.toys[e.toyId!]?.mapId||e.mapId||s.dinosaurGarden!.activeMapId)).then(ok=>{if(ok){choose(e.toyId!);setTab('garden');closeSheet();setFocus({id:e.toyId!,before:e.before?.pose});setNotice(e.summary);}});}};
  const putOnTable=()=>void commit(s=>editDino(s,user,selected,{pose:findGardenSpace(s,selected)}),'它来到箱庭了。').then(ok=>{if(ok){setTab('garden');closeSheet();}});
  const runVisit=async()=>{const char=characters.find(c=>c.id===visitor);if(!char||trip)return;setTrip(true);setError('');try{const result=await onCharacterTrip(char);if(!result.ok)throw new Error(result.reason==='no-api'?'请先配置角色或彼方 API':result.reason==='empty'?'这次回复没有给出可执行的来访动作':result.reason==='busy'?'角色正在进行另一项活动':result.reason||'这次来访没有完成');setState(syncGardenToys(readFishingMarketState()));setNotice(`${char.name}来过了，看看新便签。`);closeSheet();}catch(e){setError((e as Error).message);}finally{setTrip(false);}};
  return <main className="clay-app" data-ready={ready} data-sheet={sheet||''} role="dialog" aria-modal="true" aria-label="艾文的恐龙箱庭">
    <header className="clay-header"><button className="clay-back" aria-label="返回 SAR 活动室" onClick={onClose}>‹</button><div><span className="clay-eyebrow">{demo?'箱庭试玩 · 示例藏品':'SAR · CLAY DINOSAURS'}</span><h1>艾文的恐龙箱庭</h1></div><button className="clay-theme" disabled={!g} onClick={()=>open('theme')}>{map?.name||'地图'} ⌄</button></header>
    <nav className="clay-tabs" aria-label="箱庭与图鉴"><button aria-pressed={tab==='garden'} onClick={()=>{setTab('garden');closeSheet();engine.current?.reset();}}>箱庭</button><button aria-pressed={tab==='catalog'} onClick={()=>{setTab('catalog');closeSheet();setPlacing(null);}}>图鉴</button></nav>
    <div className="clay-scene" ref={host} style={{visibility:tab==='catalog'&&!portrait?'hidden':undefined}}/>
    {tab==='garden'&&!sheet&&<div className="clay-map-caption">{map?.name} · {residents.length} / 6 只{placing?' · 隐藏格子已亮起':' · 拖动转一转'}</div>}
    {tab==='garden'&&!sheet&&<div className="clay-scene-tools"><button aria-label="还原视角" onClick={()=>engine.current?.reset()}>↺</button><button onClick={()=>open('props')}>摆件</button><button onClick={()=>open('visits')}>来访</button></div>}
    {!ready&&!error&&<div className="clay-loading">橡皮泥小朋友正在就位…</div>}
    {(error||notice||placing)&&<div className={'clay-toast'+(error?' is-error':'')} role={error?'alert':'status'}>{error||notice||(placing?.startsWith('prop:')?'点一块空地摆好摆件':'点一个亮起的落点，把它摆过去')}<button aria-label="关闭提示" onClick={()=>{setError('');setNotice('');}}>×</button></div>}
    {tab==='garden'&&!sheet&&<>
      {!!unread.length&&<button className="clay-unread" onClick={()=>showHistory(true)}>{unread.at(-1)?.actorName}来过 · {unread.length} 件新变化 <span>看看 →</span></button>}
      <section className="clay-tray" aria-label="当前恐龙">
        <div className="clay-caption"><button onClick={()=>open('profile')} disabled={!toy}><i style={{background:toy?.paint.body}}/><strong>{toy?.name||'桌面还空着'}</strong><span>{toy?dinoDefinition(toy.speciesId)?.name:'选一只橡皮泥恐龙'}</span></button><button className="clay-paint-link" disabled={!editable} onClick={()=>open('paint')}>换色 ◌</button><button aria-label="这只恐龙的经历" onClick={()=>showHistory()}>足迹</button></div>
        <button className="clay-story" onClick={()=>open('stage')} disabled={!editable}>{toy?<><span>正在：{toy.stage.action}{toy.stage.byId!=='user'?` · ${toy.stage.byName}续写`:''}</span><p>{toy.stage.text||'还没有台词，先好好发一会儿呆。'}</p></>:<p>钓到的恐龙，会在这里继续它们的故事。</p>}</button>
        <div className="clay-roster">{owned.map(c=>{const t=g?.toys[c.id];if(!t)return null;return <button key={c.id} aria-label={`选择${t.name}`} aria-pressed={selected===c.id} onClick={()=>choose(c.id)}><span className="clay-icon"><DinoIcon species={c.speciesId} color={t.paint.body}/>{t.pose&&t.mapId===g?.activeMapId&&gardenCatchAvailable(state!,c.id,c.ownerId)&&<i/>}</span><span>{t.name}</span><small>{c.ownerId==='user'?'我的':c.ownerName}</small></button>;})}<button className="clay-more" onClick={()=>setTab('catalog')}>＋<span>图鉴</span></button></div>
        <div className="clay-actions"><button className="clay-primary" disabled={!editable||busy||!ready} onClick={()=>{if(!onThisMap)putOnTable();else setPlacing(placing?null:'toy');}}>{placing?'取消摆放':onThisMap?'挪个位置':toy?.pose?'搬来这里':'放进箱庭'}</button><button disabled={!editable||!onThisMap||busy} onClick={()=>void commit(s=>editDino(s,user,selected,{pose:{...s.dinosaurGarden!.toys[selected].pose!,rotation:s.dinosaurGarden!.toys[selected].pose!.rotation+Math.PI/4}}))}>转向 ↻</button><button disabled={!editable} onClick={()=>open('stage')}>正在做…</button><button disabled={!toy||!ready} onClick={()=>{engine.current?.greet();setNotice(`${toy!.name}轻轻晃了晃。`);}}>打招呼</button></div>
      </section></>}
    {tab==='catalog'&&!portrait&&<section className="clay-catalog"><div className="clay-section-intro"><h2>一盒橡皮泥小朋友</h2><p>已发现 {DINO_CATALOG.filter(d=>state?.discovered.includes(d.id)).length} / {DINO_CATALOG.length} 种 · 每一只都有自己的来历</p></div><div className="clay-species-grid">{DINO_CATALOG.map(d=>{const known=state?.discovered.includes(d.id),instances=Object.values(g?.toys||{}).filter(t=>t.speciesId===d.id),mine=owned.filter(c=>c.speciesId===d.id);return <button key={d.id} className={!known?'is-unknown':''} onClick={()=>{if(instances.length){choose(mine[0]?.id||instances[0].catchId);open('details');}else setNotice(known?'曾经发现过它，这份旧存档没有留下单只记录。':'再去水域试试运气，也许下次就是它。');}}><DinoIcon species={d.id} color={known?d.body:'#bdc2af'}/><strong>{known?d.name:'尚未遇见'}</strong><span>{known?mine.length?`共有 ${mine.length} 只`:'曾经发现':'橡皮泥藏品'}</span></button>;})}</div></section>}
    {sheet&&<div className={'clay-sheet-wrap '+(portrait?'is-portrait':'')}><button className="clay-scrim" aria-label="关闭面板" onClick={closeSheet}/><section className="clay-sheet" role="dialog" aria-modal="true" aria-label={{paint:'恐龙换色',stage:'正在做什么',theme:'选择地图',props:'桌面摆件',visits:'角色来访',history:'箱庭足迹',profile:'这只恐龙',details:'恐龙图鉴详情'}[sheet]}>
      <div className="clay-sheet-head"><h2>{{paint:'给橡皮泥换个颜色',stage:'它正在做什么？',theme:'今天去哪里玩？',props:'桌上的小东西',visits:'让角色来坐一会儿',history:'留在桌上的足迹',profile:toy?.name||'这只恐龙',details:dinoDefinition(toy?.speciesId||'')?.name||'恐龙图鉴'}[sheet]}</h2><button aria-label="关闭面板" onClick={closeSheet}>×</button></div>
      {sheet==='paint'&&paint&&toy&&<><p className="clay-muted">换身体和小细节的颜色，眼睛与表情会保留。</p><div className="clay-palettes">{DINO_PALETTES.map(p=><button key={p.name} aria-label={`配色${p.name}`} aria-pressed={p.body===paint.body&&p.accent===paint.accent} onClick={()=>setPaint({body:p.body,accent:p.accent})}><span style={{background:p.body}}><i style={{background:p.accent}}/></span>{p.name}</button>)}</div><div className="clay-colors"><label>身体<input aria-label="身体颜色" type="color" value={paint.body} onChange={e=>setPaint({...paint,body:e.target.value})}/></label><label>角、背板与细节<input aria-label="细节颜色" type="color" value={paint.accent} onChange={e=>setPaint({...paint,accent:e.target.value})}/></label><button onClick={()=>setPaint(defaultDinoPaint(toy.speciesId))}>原来的颜色</button></div><button className="clay-primary clay-wide" disabled={busy||!editable} onClick={()=>void commit(s=>editDino(s,user,selected,{paint}),'新配色保存好了。').then(ok=>{if(ok)closeSheet();})}>就用这个颜色</button></>}
      {sheet==='stage'&&toy&&<><div className="clay-action-tags">{DINO_ACTIONS.map(a=><button key={a} aria-pressed={action===a} onClick={()=>setAction(a)}>{a}</button>)}</div><label className="clay-field">和谁／看什么<select aria-label="行为对象" value={target} onChange={e=>setTarget(e.target.value)}><option value="">自己待着</option>{residents.filter(t=>t.catchId!==selected).map(t=><option key={t.catchId} value={t.catchId}>{t.name}</option>)}{map?.props.map(p=><option key={p.id} value={p.id}>{PROP_LABELS[p.kind]}</option>)}</select></label><label className="clay-field">给这段小剧场写一句话<textarea aria-label="小剧场描述" maxLength={160} value={words} placeholder="坚信薄荷欠自己一块饼干。" onChange={e=>setWords(e.target.value)}/></label>{toy.stage.byId!=='user'&&<p className="clay-muted">{toy.stage.byName}后来写过：{toy.stage.text}。旧记录会保留。</p>}<button className="clay-primary clay-wide" disabled={busy||!editable} onClick={()=>void commit(s=>editDino(s,user,selected,{stage:{action,text:words,targetId:target||undefined}})).then(ok=>{if(ok)closeSheet();})}>把这句留在桌上</button></>}
      {sheet==='theme'&&<><p className="clay-muted">所有角色共用这些小地图，每张最多 6 只。搬家会保留名字、配色与经历。</p><div className="clay-theme-options">{g?.maps.map(m=><button key={m.id} aria-pressed={g.activeMapId===m.id} disabled={busy} onClick={()=>void commit(s=>setGardenMap(s,m.id)).then(ok=>{if(ok){setSelected(state?gardenResidents(state,m.id)[0]?.catchId||owned[0]?.id||'':'');closeSheet();engine.current?.reset();}})}><span className={`clay-landscape ${m.theme}`}/><strong>{m.name}</strong><small>{state?gardenResidents(state,m.id).length:0} / 6 只 · {m.theme==='grassland'?'小山坡与溪边营地':m.theme==='coast'?'贝壳、浅水与海边小屋':'圆圆的火山与探险营地'}</small></button>)}</div></>}
      {sheet==='props'&&<><p className="clay-muted">桌上 {map?.props.length} / 12 件。选中后点空地，摆件就能挪过去。</p><div className="clay-prop-add">{Object.entries(PROP_LABELS).map(([kind,label])=><button key={kind} disabled={busy} onClick={()=>void commit(s=>editGardenProp(s,user,{kind:kind as GardenPropKind}))}>＋ {label}</button>)}</div><div className="clay-prop-list">{map?.props.map(p=><div key={p.id}><span>{PROP_LABELS[p.kind]}</span><button onClick={()=>{setPlacing('prop:'+p.id);closeSheet();}}>挪动</button><button disabled={busy} onClick={()=>void commit(s=>editGardenProp(s,user,{id:p.id,pose:{...p,rotation:p.rotation+Math.PI/4}}))}>转向</button><button disabled={busy} onClick={()=>void commit(s=>editGardenProp(s,user,{id:p.id,remove:true}))}>收起</button></div>)}</div></>}
      {sheet==='visits'&&<><label className="clay-toggle"><span>共同摆弄<small>允许已接入彼方的角色留便签、挪动恐龙和续写状态。固定的恐龙只收便签。</small></span><input type="checkbox" aria-label="共同摆弄" checked={!!g?.visitsEnabled} disabled={busy} onChange={e=>{const checked=e.currentTarget.checked;void commit(s=>setGardenVisits(s,checked,user));}}/></label><p className="clay-muted">自动来访发生在彼方运行时。关闭应用期间暂不会产生新的来访。</p><label className="clay-field">现在邀请一位<select aria-label="选择来访角色" value={visitor} onChange={e=>setVisitor(e.target.value)}><option value="">选择角色</option>{characters.filter(c=>c.vrState?.enabled).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="clay-primary clay-wide" disabled={!visitor||trip||!g?.visitsEnabled||!residents.length} onClick={()=>void runVisit()}>{trip?'正在走过来看…':'请 ta 来看看'}</button><p className="clay-muted">每次邀请调用一次角色模型。自动来访有间隔，不补刷错过的日子。</p></>}
      {sheet==='history'&&<><div className="clay-history">{history.slice(historyPage*15,historyPage*15+15).map(e=><article key={e.id}><small>{e.actorName} · {stamp(e.at)}</small><p>{e.summary}</p>{e.words&&<blockquote>{e.words}</blockquote>}<div>{e.toyId&&<button onClick={()=>focusEvent(e)}>看看它</button>}{e.before&&e.actorKind==='character'&&g?.toys[e.toyId||'']?.revision===e.afterRevision&&!g?.events.some(n=>n.undoOf===e.id)&&<button disabled={busy} onClick={()=>void commit(s=>undoGardenVisit(s,e.id,user))}>还原这次改动</button>}</div></article>)}</div><div className="clay-pager"><button disabled={!historyPage} onClick={()=>setHistoryPage(p=>p-1)}>较新</button><span>{historyPage+1}</span><button disabled={(historyPage+1)*15>=history.length} onClick={()=>setHistoryPage(p=>p+1)}>更早</button></div><label className="clay-field">接着留一句<textarea aria-label="回应便签" value={words} maxLength={240} onChange={e=>setWords(e.target.value)} placeholder="她赢了就是赢了。"/></label><button className="clay-primary clay-wide" disabled={busy||!words.trim()} onClick={()=>void commit(s=>gardenComment(s,user,selected||undefined,words)).then(ok=>{if(ok)setWords('');})}>留下便签</button></>}
      {sheet==='profile'&&toy&&<><label className="clay-field">它的名字<input aria-label="恐龙名字" value={nickname} maxLength={16} onChange={e=>setNickname(e.target.value)}/></label><button className="clay-primary clay-wide" disabled={busy||!editable||!nickname.trim()} onClick={()=>void commit(s=>editDino(s,user,selected,{name:nickname})).then(ok=>{if(ok)closeSheet();})}>保存名字</button><label className="clay-toggle"><span>固定这只<small>角色可以评论，但不能挪动或续写它的状态。</small></span><input aria-label="固定这只恐龙" type="checkbox" checked={toy.fixed} disabled={busy||!editable} onChange={e=>{const fixed=e.currentTarget.checked;void commit(s=>editDino(s,user,selected,{fixed}));}}/></label><div className="clay-inline"><button onClick={()=>open('details')}>近看与来历</button><button disabled={!editable||!toy.pose||busy} onClick={()=>void commit(s=>editDino(s,user,selected,{pose:null})).then(ok=>{if(ok)closeSheet();})}>收进盒子</button></div><label className="clay-field">送给<select aria-label="赠送给角色" value={giftTarget} onChange={e=>setGiftTarget(e.target.value)}><option value="">选择角色</option>{characters.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button className="clay-wide" disabled={!giftTarget||!editable||busy||state?.inventory.find(c=>c.id===selected)?.ownerId!=='user'} onClick={()=>{const c=characters.find(c=>c.id===giftTarget);if(c)void commit(s=>giftDino(s,user,selected,{id:c.id,name:c.name,kind:'character'}),'已经送给 ta，名字与经历也一起带过去了。').then(ok=>{if(ok)closeSheet();});}}>把这只送给 ta</button></>}
      {sheet==='details'&&toy&&<><div className="clay-detail-name"><strong>{toy.name}</strong><span>{state?.inventory.find(c=>c.id===selected)?.ownerName||'留在记录里的小朋友'}</span></div><p className="clay-fact">{dinoDefinition(toy.speciesId)?.fact}</p><p className="clay-muted">{toy.origin.kind==='fished'?`${toy.origin.actorName}钓到了它`:toy.origin.kind==='gift'?`${toy.origin.actorName}送出的橡皮泥模型`:'旧存档未记录最初的获得者'} · {stamp(toy.origin.at)}</p><div className="clay-instances">{Object.values(g?.toys||{}).filter(t=>t.speciesId===toy.speciesId).map(t=><button aria-pressed={selected===t.catchId} key={t.catchId} onClick={()=>choose(t.catchId)}>{t.name}</button>)}</div><div className="clay-inline"><button onClick={()=>showHistory()}>这只的足迹</button><button disabled={!editable} onClick={()=>open('paint')}>换个颜色</button>{editable&&<button className="clay-primary" disabled={busy} onClick={()=>{if(onThisMap){setTab('garden');closeSheet();}else putOnTable();}}>去箱庭</button>}</div></>}
    </section></div>}
  </main>;
}
